### ISSUE TITLE
Whole method is rollbacked for specific assignment

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#1745]
**Describe the bug**
Since the introduction of the block mutator it's clear rollbacking assignment errors isn't correct.

```csharp
        public void SomeLinq()
        {
            var list = new List<List<double>>();
            var something = 1 + 3;
            int[] listProjected = list.Select(l => l.Count()).ToArray();
        }
```

In the above method all mutations are rollbacked. The linq select mutation (Count to Sum) changes the return value from double to int. So the assignment will fail.

**Comment by dupdob** [comment]
Do you mean the problem is in a branch or is it fixed now ? 
Just asking because I was interested (mostly curious) in fixing this 😄 .

**Comment by richardwerkman** [comment]
The problem is still present. In that commit there is a test that displays the issue. On master I changed that test so it won't fail. So it you checkout the above commit you should see what the issue is

**Comment by dupdob** [comment]
I did not try this commit, as I don't want to go through the hassle of reintegrating any change back in the head.
But I saw this [comment](https://github.com/stryker-mutator/stryker-net/blob/18b5a5dbbabbce6cdb5cb3387923bad5c03637f2/src/Stryker.Core/Stryker.Core.UnitTest/Compiling/RollbackProcessTests.cs#L162) but it does not match your description of the issue.

Yes, there are more than mutations which is rolled back, but this does not trigger a removal of mutations from the method (aka safe mode). In fact, the mutation for `var something = 1 + 3;` are kept in the final compilation.

But the _block_ mutation is rolled back alongside with the _Linq_ mutation. I will look into this, but this is less serious than it appears.
It may be the signal of something wrong with the block mutator.

**Comment by dupdob** [comment]
ok,
this is due to the rollback logic scanning UP the syntax tree before scanning down. So it first removes the enclosing block mutator, which does not resolve the problem and then digs into the expression and removes the Linq mutation.

**Comment by dupdob** [comment]
I have changed the scanning logic to dig into expression before moving up. All tests are ok.
Testing this with NFluent.
I think next step will be to see if I can add some stop conditions (scanning up and/or down) to improve performance

**Comment by rouke-broersma** [comment]
@dupdob we had actually tried the same already and had also decided that scanning down before scanning up causes way too many mutations to be removed when they are perfectly valid otherwise.

**Comment by dupdob** [comment]
that is what I figured out. working on this

**Comment by dupdob** [comment]
update: the work to do appears harder by the day. I think the two most complicated things are: 
1. restoring rolledback mutations
2. tracking errors across mutant versions
But, I just found out yesterday that my initial problem (excessive number of compile error) was **due to the block mutator** and not to the mutation identification strategy (upward vs downward). Initial count was close to 500. Integrating V 1.0.1 reduced it in half. So I still have 200 compile error due to block mutator.

I will look into to, but I am afraid I start to think that block mutation is not a good fit in its current form

**Comment by dupdob** [comment]
update: digging into these issues revealed that anonymous function orchestrator was missing (as well as helper engines). This was already a potential issue, but BlockMutator exacerbates the problem. I am currently adding them.

**Comment by dupdob** [comment]
Update:
I have stopped working on this. The main difficulty I hit is being able to restore mutations when they have been removed; but also I realized that it was far harder than I thought:
My strategy was: when there is an error occurring without any clear causing mutations, remove each mutations (from the method/function/Accessor...) until the error goes away. Alas, I realized that several mutations can trigger the same error message (any _using undefined variable_ for example). Therefore, the only way was then to test every mutation combination until the error goes away. Which means that if you have 10 mutations in a method, you end up with several hundreds of combinations to test; if you have 20 or more mutations, you reach 10's or even 100's k combinations.

This is not realistic. I feel we need to get rid of the block mutator OR apply it in a more restricted fashion, eg: whole body at once. We could also scan for problematic statements, but I fear this may be an endless chase of subtle syntax constructions: for example, a local variable can be initialized by as an `out` parameter... in some locally defined function.

**Comment by rouke-broersma** [comment]
It does feel like we should at least temporarily disable the block mutator by default because it causes major issues in even small projects. @richardwerkman ?

**Comment by richardwerkman** [comment]
We could also implement the feature I suggested: only place block mutations when it doesn't contain other mutations. This issue would never occur in that case. And we remove equivalent mutations. So that sounds like the perfect solution to me. But I couldn't yet get that to work. 

For now I can live with removing the Block mutator temporarily. But we have to think of a permanent solution for this

**Comment by dupdob** [comment]
I am afraid this is not sufficient. I think the following example demonstrates it:
```csharp
var x= 0;
if (predicate)
{
 x = 1;
}
else if (other_predicate)
{
 x = 2;
}
else
{
 x = 3;
}
return x;
```
would generate 3 block mutations which would all trigger a `using uninitialized variable 'x'`. Which would be difficult to remove and would trigger a removal of every mutations within this method.

**Comment by dupdob** [comment]
I just got another idea: aggressively removes block mutations instead of safe mode.
That is, if Stryker can't link the error message to a specific mutations, it rolls back every  block mutation (from the current method) and tries again. Safe mode is only triggered if there is no block mutation present.
This would allow for block mutations without compromising existing ones.
what do you think?

**Comment by richardwerkman** [comment]
@dupdob sounds like a great idea! We could roll back block mutation first. Then statement mutations and if those didn't help fall back to safe mode. I like this better than just turning off block mutations as a whole

**Comment by dupdob** [comment]
FYI: I am looking into this. The  unanticipated hassle is that `RollbackProcess` has no data on the mutations themselves.

**Comment by richardwerkman** [comment]
I also looked into this. I have a working solution ready but am still working on tests

**Comment by dupdob** [comment]
I stop my effort then. For information, I also improved the selectivity of the blockmutator to prevent some common compilation errors

**Comment by dupdob** [comment]
I think we can safely close this now
