### ISSUE TITLE
Compiler error when using GeneratedRegexAttribute

### ISSUE THREAD

**Issue by AntarEspadas** [stryker-mutator/stryker-net#2398]
**Describe the bug**

If the source code contains a regex that uses [regular expression source generation](https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generatorsl), Stryker fails to build the project.

**Logs**

```log
[12:02:26 INF] Identifying project to mutate.
[12:02:27 INF] The project /home/antar/repos/StrykerGeneratedRegexBug/StrykerGeneratedRegexBug/StrykerGeneratedRegexBug.csproj will be mutated.
[12:02:29 INF] Analysis complete.
[12:02:29 INF] Building test project /home/antar/repos/StrykerGeneratedRegexBug/Tests/Tests.csproj (1/1)
[12:02:38 INF] Total number of tests found: 1.
[12:02:38 INF] Initial testrun started.
[12:02:41 WRN] Stryker.NET encountered an compile error in /home/antar/repos/StrykerGeneratedRegexBug/StrykerGeneratedRegexBug/ClassWithGeneratedRegex.cs (at 7:25) with message: Partial method 'ClassWithGeneratedRegex.SampleRegex()' must have an implementation part because it has accessibility modifiers. (Source code: [GeneratedRegex("a")]
    public partial Regex SampleRegex();)
[12:02:41 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
[12:02:41 WRN] Stryker.NET encountered an compile error in /home/antar/repos/StrykerGeneratedRegexBug/StrykerGeneratedRegexBug/ClassWithGeneratedRegex.cs (at 7:25) with message: Partial method 'ClassWithGeneratedRegex.SampleRegex()' must have an implementation part because it has accessibility modifiers. (Source code: [GeneratedRegex("a")]
    public partial Regex SampleRegex();)
[12:02:41 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
[12:02:41 WRN] Stryker.NET encountered an compile error in /home/antar/repos/StrykerGeneratedRegexBug/StrykerGeneratedRegexBug/ClassWithGeneratedRegex.cs (at 7:25) with message: Partial method 'ClassWithGeneratedRegex.SampleRegex()' must have an implementation part because it has accessibility modifiers. (Source code: [GeneratedRegex("a")]
    public partial Regex SampleRegex();)
[12:02:41 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
[12:02:41 WRN] Stryker.NET encountered an compile error in /home/antar/repos/StrykerGeneratedRegexBug/StrykerGeneratedRegexBug/ClassWithGeneratedRegex.cs (at 7:25) with message: Partial method 'ClassWithGeneratedRegex.SampleRegex()' must have an implementation part because it has accessibility modifiers. (Source code: [GeneratedRegex("a")]
    public partial Regex SampleRegex();)
```

**Expected behavior**

Stryker should build the project and run the tests

**Desktop (please complete the following information):**
 - OS: Linux
 - Type of project: core
 - Framework Version: 7
 - Stryker Version: 3.4.0

**Additional context**

A repo that reproduces the error can be found [here](https://github.com/Naratna/StrykerGeneratedRegexBug)

**Comment by dupdob** [comment]
thanks for reporting this and providing a reproduction repo. I have some good new. It seems this problem has been fixed by a recent release, or the upcoming one: I did not encounter any issue with your repo with the development version.

Could you please try your project against V3.9 and report if this is still an issue ?

**Comment by Naratna** [comment]
Hi. The issue doesn't appear to be fixed on version 3.9, I still get the same error message

**Comment by dupdob** [comment]
Sorry to hear that. As said earlier, I dit not have any problem with the project you provided. 
Does this project work on your set up? If no, it is probably somehow related to your set up, while I have no idea what could cause this. 

If this project works on your machine, I think you need to change it somehow till you reproduce the problem.

**Comment by Naratna** [comment]
Well, I just tried reproducing the bug on my laptop and the project runs fine, which means that, as you said, it's probably related to the environment on my desktop PC.

I'll send the log file later, in case you're still interested in looking into this.

**Comment by dupdob** [comment]
yes please

**Comment by Naratna** [comment]
Ah, completely forgot to send the logs. Apologies

[logs.zip](https://github.com/stryker-mutator/stryker-net/files/11715180/logs.zip)

**Comment by dupdob** [comment]
no longer an issue
